paths:
  dependencies:
    conda_env: pipeline-cfMeDIP-core
    medestrand_path: /cluster/home/asinghaw/git/MeDEStrand
  bwa: /cluster/home/asinghaw/software/conda/envs/pipeline-cfMeDIP-core/bin/bwa
  bwa_index: /cluster/projects/scottgroup/people/althaf/assets/reference/genomes/hg38_arabidopsis_chr_1_3/BWA_index/hg38_arabidopsis_chr_1_3.fa
  samtools: /cluster/home/asinghaw/software/conda/envs/pipeline-cfMeDIP-core/bin/samtools
  genome: /cluster/projects/scottgroup/people/althaf/assets/reference/genomes/hg38_arabidopsis_chr_1_3/hg38_arabidopsis_chr_1_3.fa
  bpattern: NNT
  barcodes: /cluster/projects/scottgroup/people/althaf/assets/reference/barcodes/barcode_idt.txt
  bsgenome:
    human: BSgenome.Hsapiens.UCSC.hg38
    arabidopsis: BSgenome.Athaliana.TAIR.TAIR9
data:
  base_path: /cluster/projects/scottgroup/people/althaf/pipelines/cfmedipseq_pipeline
  cohorts:
    Justin_HN_Norm_cfDNA_PBL:
      cohort_name: Justin_HN_Norm_cfDNA_PBL
      samplesheet: /cluster/projects/scottgroup/people/althaf/pipelines/cfmedipseq_pipeline/input/cohorts/samplesheet_Justin_HN_Norm_cfDNA_PBL.csv
      active: True
    test:
      cohort_name: test
      samplesheet: /cluster/projects/scottgroup/people/althaf/pipelines/cfmedipseq_pipeline/input/cohorts/samplesheet_comparison_cfmedip_test.csv
      active: False
    dummy:
      cohort_name: dummy
      samplesheet: /cluster/home/asinghaw/git/cfmedipseq_pipeline/dummyfiles/dummy_samplesheet.csv
      active: False
